# To see the complete list of configurable parameters see:
# https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py
"framework": "torch"
"horizon": 1000
"num_workers": 15
"num_gpus_per_worker": 0.25
"num_cpus_per_worker": 3
"rollout_fragment_length": 16
"horizon": 6400
"timesteps_per_iteration": 15000
"train_batch_size": 64
"learning_starts": 15000
"buffer_size": 20000
"lr": 0.005
"exploration_config": {
  "type": "EpsilonGreedy",
  "initial_epsilon": 1.0,
  "final_epsilon": 0.02,
  "epsilon_timesteps": 2000000
}
"hiddens": [256, 512]
"model": {
  "dim": 300,
  "conv_filters": [
    [16, [5, 5], 4],
    [32, [5, 5], 2],
    [32, [5, 5], 2],
    [64, [5, 5], 1],
    [64, [5, 5], 2],
    [128, [5, 5], 2],
    [512, [5, 5], 1],
  ]
}

env_config:
  carla:
    host: "localhost"
    timeout: 10.0
    timestep: 0.05
    retries_on_error: 25
    resolution_x: 600
    resolution_y: 600
    quality_level: "Low"
    enable_map_assets: True
    enable_rendering: True
    show_display: True

  experiment:
    hero:
      blueprint: "vehicle.lincoln.mkz2017"
      sensors:
        collision:
          type: "sensor.other.collision"
        birdview:
          type: "sensor.birdview"
          size: 300
          radius: 15
      spawn_points: [
        "-130.80254883,103.26209961,2",  # x,y,z[,roll,pitch,yaw]
        "-258.58019531,0.32128639,2",
        "-130.50441406,136.6653125,2",
        "-258.58871094,-3.82127594,2",
        "-188.099101566,-101.55841797,2",
        "-120.81304688,-127.37759766,2",
        "143.90660156,1.53764084,2",
        "-51.00605469,112.90189453,2",
        "-127.00455078,136.63408203,2",
        "229.64353516,-95.19664062,2",
        "-248.39375,86.93456055,2",
        "82.57344727,-143.86496094,2",
        "60.38806641,-87.59395508,2",
        "76.17259766,145.39817383,2"
        ]
    background_activity:
      n_vehicles: 0
      n_walkers: 0
      tm_hybrid_mode: True
    town: "Town05_Opt"
    others:
      framestack: 4
      max_idle: 600