# Works for both torch and tf.
num_workers: 1
num_gpus: 1
num_cpus_per_worker: 11
framework: torch
gamma: 0.99
twin_q: True
q_model_config:
    hidden_activation: relu
    hidden_layer_sizes: [256,512]
policy_model_config:
    hidden_activation: relu
    hidden_layer_sizes: [256,512]


recreate_failed_workers: True
# Do hard syncs.
# Soft-syncs seem to work less reliably for discrete action spaces.
tau: 1.0
target_network_update_freq: 8000
# auto = 0.98 * -log(1/|A|)
target_entropy: auto
clip_rewards: False
n_step: 1
rollout_fragment_length: 1
replay_buffer_config:
  type: MultiAgentPrioritizedReplayBuffer
  capacity: 400000
  # How many steps of the model to sample before learning starts.
  # If True prioritized replay buffer will be used.
  prioritized_replay_alpha: 0.6
  prioritized_replay_beta: 0.4
  prioritized_replay_eps: 0.000001
store_buffer_in_checkpoints: False
num_steps_sampled_before_learning_starts: 10000
train_batch_size: 64
min_sample_timesteps_per_iteration: 4
lr:  0.001
# Paper uses 20k random timesteps, which is not exactly the same, but
# seems to work nevertheless. We use 100k here for the longer Atari
# runs (DQN style: filling up the buffer a bit before learning).
optimization:
    actor_learning_rate: 0.001
    critic_learning_rate: 0.001
    entropy_learning_rate: 0.001

"exploration_config": {
  "type": "Curiosity",
#  "initial_epsilon": 1.0,
#   "final_epsilon": 0.01,
#   "epsilon_timesteps": 400000
}
#num_workers: 1
#num_gpus: 1
##num_gpus_per_worker: 1
#num_cpus_per_worker: 11
##timesteps_per_iteration: 20000
#
#num_steps_sampled_before_learning_starts: 2500
#recreate_failed_workers: True
#replay_buffer_config: {
#  capacity: 100000
#}
#
#
## "batch_mode": "complete_episodes"
#

#target_network_update_freq: 8000
#exploration_config: {
#  type: "SoftQ",
#  temperature: 1.0,
#}

#hiddens: [256, 512]
#model: {
#  dim: 300,
#  conv_filters: [
#    [16, [5, 5], 4],
#    [32, [5, 5], 2],
#    [32, [5, 5], 2],
#    [64, [5, 5], 1],
#    [64, [5, 5], 2],
#    [128, [5, 5], 2],
#    [512, [5, 5], 1],
#  ]
#}

env_config:
  carla:
    host: "192.168.1.113"
#    host: "172.17.0.1"
#   host: "127.0.0.1"
    programPort: "5418"
    timeout: 30.0
    # IF YOU ARE GOING TO CHANGE THE TIMESTEP CHANGE rotation_frequency of LIDAR
    timestep: 0.1 # IMP IMP
    # IMP
    retries_on_error: 25
    resolution_x: 300
    resolution_y: 300
    quality_level: "Low"
    enable_map_assets: True
    enable_rendering: False
    show_display: True
    map_buffer : 1.2
    truckTrailerCombo: True


  experiment:
    hero:
      truckTrailerCombo: True
      blueprintTruck: "vehicle.daf.dafxf"
#      blueprintTruck: "vehicle.audi.a2"
      blueprintTrailer: "vehicle.trailer.trailer"
      lidar_max_points : 3000
      sensors:
#        obstacle:
#          type: "sensor.other.obstacle"
        collision:
          type: "sensor.other.collision"
#        depth_camera:
#          type: "sensor.camera.depth"
#          image_size_x: 84
#          image_size_y: 84
#          transform: '0.0,0.0,1.7,0.0,0.0,0.0' # x,y,z,pitch, yaw, roll
#        lidar:
#          type: "sensor.lidar.ray_cast_semantic"
#          channels : "32"
#          range : "50.0"
#          points_per_second : "50000"
#          rotation_frequency : "10" #  IMP THIS IS 1 / delta (timestep)
#          upper_fov : '5.0'
#          lower_fov : '-90.0'
#          horizontal_fov : '360.0'
#          sensor_tick : '0'
#          transform : '2,0.21,8,0.0,0.0,0.0' # x,y,z,pitch, yaw, roll
#        semantic_camera:
#          type: "sensor.camera.semantic_segmentation"
#          transform: '0.0,0.0,1.7,0.0,0.0,0.0' # x,y,z,pitch, yaw, roll
      #        laneInvasion:
#          type: "sensor.other.lane_invasion"
      spawn_points: [
         "5.1,54.2,1",  # x,y,z[,roll,pitch,yaw]
        "5.7,117.7,1",
        "2.0,97.2,1",
        "1.8,87.6,1",
        "4.5,47.0,1",
        "8.3,25.0,1",
         "20.0,11.5,1",
         "36.9,7.1,1",
        ]
      final_location_x: 56.4
      final_location_y: 7.5
    background_activity:
      n_vehicles: 0
      n_walkers: 0

      tm_hybrid_mode: True
#    town: "Town03_Opt"
    town: 'doubleRoundabout37'
    others:
      framestack: 1
      max_time_idle: 600
      max_time_episode: 6400
