# To see the complete list of configurable parameters see:
# https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py
framework: "torch"
num_workers: 6
num_gpus: 1
#gpu: True
#num_gpus_per_worker: 1
num_cpus_per_worker: 3
recreate_failed_workers: True
#timesteps_per_iteration: 20000
#horizon: 6500

double_q: true
dueling: false
#num_atoms: 51
#noisy: True
gamma: 0.99
lr: 0.0001
#lr: .0001
hiddens: [100,100,100,100]
#rollout_fragment_length: 4
train_batch_size: 16
"exploration_config": {
  "type": "EpsilonGreedy",
  "initial_epsilon": 1.0,
  "final_epsilon": 0.01,
  "epsilon_timesteps": 1000000
}
#target_network_update_freq: 500
replay_buffer_config:
  type: MultiAgentPrioritizedReplayBuffer
  capacity: 600000
  # How many steps of the model to sample before learning starts.
  # If True prioritized replay buffer will be used.
  prioritized_replay_alpha: 0.6
  prioritized_replay_beta: 0.4
  prioritized_replay_eps: 0.000001
num_steps_sampled_before_learning_starts: 10000
#n_step: 1


#model: {
##  use_lstm: True,
#  grayscale: True,
#  dim: 128,
#  conv_filters: [
#    [16, [5, 5], 2],
#    [32, [5, 5], 2],
#    [64, [5, 5], 2],
#    [128, [5, 5], 2],
#    [256, [5, 5], 2],
#    [516, [4,4], 1],
#  ]
#}


env_config:
  carla:
#    host: "192.168.1.113"
#    host: "172.17.0.1"
    host: "127.0.0.1"
    programPort: "5418"
    timeout: 30.0
    # IF YOU ARE GOING TO CHANGE THE TIMESTEP CHANGE rotation_frequency of LIDAR
    timestep: 0.1 # IMP IMP
    # IMP
    retries_on_error: 25
    resolution_x: 300
    resolution_y: 300
    carla_location: '/home/daniel/carla/Dist/CARLA_Shipping_0.9.13-1-g8854804f4-dirty/LinuxNoEditor'
    quality_level: Low
    enable_map_assets: True
    enable_rendering: True
    show_display: True
    map_buffer : 1.2
    truckTrailerCombo: True


  experiment:
    hero:
      truckTrailerCombo: True
      blueprintTruck: "vehicle.daf.dafxf"
#      blueprintTruck: "vehicle.audi.a2"
#      blueprintTrailer: "vehicle.trailer.trailer"
      blueprintTrailer: "vehicle.trailershort.trailershort"
      paperImplementation: 'True'
      lidar_max_points : 3000
      sensors:
#        obstacle:
#          type: "sensor.other.obstacle"
        collision:
          type: "sensor.other.collision"
        trailer_lidar:
          type: "sensor.lidar.ray_cast_semantic"
          horizontal_fov: '360.0'
          rotation_frequency: "10" #  IMP THIS IS 1 / delta (timestep)
          upper_fov: '-79'
          lower_fov: '-90'
          points_per_second: "500000"
          range: '165.5'
          sensor_tick: '0'
          channels: '64'
          transform: '0,0,162.8,0,0,0' # x,y,z,pitch, yaw, roll
#        trailer_radar:
#          type: "sensor.other.radar"
#          horizontal_fov: "360"
#          range: '165.5'
#          vertical_fov: '90'
#          transform: '0,0,1,0,0,0' # x,y,z,pitch, yaw, roll




    background_activity:
      n_vehicles: 0
      n_walkers: 0

      tm_hybrid_mode: True
#    town: "Town03_Opt"
#    town: 'doubleRoundabout37'
    town1: 'mediumRoundabout4'
    town1Ratio: 0.4
#    town2: 'doubleRoundabout37'
#    town2: 'mediumRoundabout4'
    town2 : 'None'
    town2Ratio: 0.6
#    town: '20m'
    others:
      framestack: 1
      max_time_idle: 300
      max_time_episode: 6400
      traffic: False
